repo.yml

patch: Change repo.yml repo type

---

docusaurus.config.js
docusaurusify.sh

Use process.env instead of sed

---

.github/workflows/flowzone.yml

Flowzone: use inherited secrets

---

docusaurus.config.js

After recent conversation with Lizze, we decided on the following generalized navbar + footer links
Some I can't add right now, will open an issue for them to take note. 

patch: Add Footer to theme

---

docusaurusify.sh

After discussing https://balena.zulipchat.com/#narrow/stream/348930-product-os.2Fflowzone/topic/more.20website.20inputs.20vs.20separate.20config.20file, this felt like the best of both worlds. 
Atleast this will help me unblock my progress. 

patch: Add balena-docs as path to look for docs

---

docusaurusify.sh

Added the missing the forward slashes missing in the #19 patch

patch: Fix docusaurusify script DOCS_PATH variable

---

docusaurusify.sh

Appending leads to results like this: 

patch: Copy README file instead of appending

---

docs/README.md
docusaurusify.sh

patch: Copy README if it doesn't exist

---

docs/README.md
docusaurusify.sh
extract-meta.sh

Adds ability to override default project name and taglines.

Adds support for overriding PROJECT_NAME and TAGLINE

---

docusaurusify.sh

Fixed extract command

---

docusaurusify.sh
extract-meta.sh

Fixed file paths

---

docusaurus.config.js

Handled logging when missing frontmatter

---

docusaurus.config.js

use correct path for readme

---

.github/workflows/flowzone.yml
README.md

Add internal documentation very specific to balena since we don't plan to productize this yet
Create a website

Add docusaurus builder docs

---

.dockerignore
.github/workflows/flowzone.yml
Dockerfile
README.md
docker-bake.hcl
docker-compose,yml
docs/README.md
docusaurus.config.js
entrypoint.sh
package.json

Adds support for building locally

---

entrypoint.sh

Fixes incorrect README.md

---

docs/README.md
docusaurus.config.js
package-lock.json
package.json

Add mermaid plugin

---

package-lock.json
package.json

Following the migration guide to upgrade Docusaurus to v3: https://docusaurus.io/blog/releases/3.0

Prepare Docusaurus for v3 upgrade

---

package-lock.json
package.json

Local search broke due to a recent upgrade of Docusaurus types, so decided to upgrade all of dependencies to latest version and resolve the issue.  
Signed-off-by: Vipul Gupta (@vipulgupta2048) <vipulgupta2048@gmail.com>

Update Docusaurus to v3.5.2

---

package-lock.json
package.json

Signed-off-by: Vipul Gupta (@vipulgupta2048) <vipulgupta2048@gmail.com>

patch: Override Cheerio to v1.0.0-rc.12

---

package-lock.json
package.json

Reverts rennovate's PR because https://github.com/cmfcmf/docusaurus-search-local/issues/214#issuecomment-2286192361 is the workaround atm to get local search working

Update overrides for cheerio to v1.0.0-rc.12

---

static/_header

Add security HTTP headers

---

README.md

Add Docusaurus unpublishing instructions
Signed-off-by: Vipul Gupta (@vipulgupta2048) <vipulgupta2048@gmail.com>

patch: Add Docusaurus unpublish instructions
